export type StakeholderStage = 'RESOLVE_PREFLIGHT' | 'APPROVE_CONTENT' | 'APPROVE_TO_PRINT';

export type InformativeEvent =
  | 'TITLE_CREATED'
  | 'FILES_UPLOADED'
  | 'TITLE_APPROVED_TO_PRINT'
  | 'TITLE_RETRIEVED_FROM_ARCHIVE'
  | 'PREFLIGHT_WARNING_ERRORS'
  | 'SPECIFICATIONS_WARNING_ERRORS'
  | 'CONTENT_APPROVAL_REQUESTED'
  | 'CONTENT_APPROVAL_APPROVED'
  | 'APPROVE_TO_PRINT_REQUESTED'
  | 'USER_WAS_CREATED'
  | 'USER_WAS_MODIFIED';
