#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "For the Apago fork, skipping commitlint - because we aren't observing the commit msg conventions of the main branch."
# npx --no-install commitlint --edit "$1"
